include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    # Best Practices
    - avoid_print
    - close_sinks
    - empty_catches
    - no_duplicate_case_values
    - only_throw_errors
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_is_empty
    - prefer_is_not_empty
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_this
    - unnecessary_await_in_return

    # Style
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_positional_boolean_parameters
    - camel_case_types
    - constant_identifier_names
    - non_constant_identifier_names
    - prefer_single_quotes
    - sort_child_properties_last
    - type_annotate_public_apis
    - unnecessary_const
    - unnecessary_new
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
