targets:
  $default:
    sources:
      - integration_test/**
      - test/**
      - lib/**
      - $package$
    builders:
      bdd_widget_test|featureBuilder:
        options:
          stepFolderName: ../integration_test/step
          includeIntegrationTestBinding: false