name: hommie_workspace
publish_to: none

environment:
  sdk: ">=3.12.2 <4.0.0"
  flutter: ^3.44.3

workspace:
  - app
  
  # Third-party local packages
  - packages/computer
  - packages/drag_arrange
  - packages/home_assistant_client
