// Mocks generated by Mockito 5.4.6 from annotations
// in home_assistant_websocket/test/ha_connection_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:home_assistant_websocket/src/connection/ha_connection_option.dart'
    as _i4;
import 'package:home_assistant_websocket/src/connection/ha_socket.dart' as _i3;
import 'package:home_assistant_websocket/src/logging/logger_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHaLogger_0 extends _i1.SmartFake implements _i2.HaLogger {
  _FakeHaLogger_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHASocket_1 extends _i1.SmartFake implements _i3.HASocket {
  _FakeHASocket_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HAConnectionOption].
///
/// See the documentation for Mockito's code generation for more information.
class MockHAConnectionOption extends _i1.Mock
    implements _i4.HAConnectionOption {
  MockHAConnectionOption() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HaLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeHaLogger_0(this, Invocation.getter(#logger)),
          )
          as _i2.HaLogger);

  @override
  _i5.Future<_i3.HASocket> createSocket() =>
      (super.noSuchMethod(
            Invocation.method(#createSocket, []),
            returnValue: _i5.Future<_i3.HASocket>.value(
              _FakeHASocket_1(this, Invocation.method(#createSocket, [])),
            ),
          )
          as _i5.Future<_i3.HASocket>);
}
