FROM python:3.11-slim

WORKDIR /app

COPY ./web-server/requirements.txt .
RUN pip install -r requirements.txt
RUN pip install homeassistant-cli

COPY ./web-server/hass_cli_web.py .

CMD ["uvicorn", "hass_cli_web:app", "--host", "0.0.0.0", "--port", "3000"]
