FROM python:3.11.11-slim@sha256:081075da77b2b55c23c088251026fb69a7b2bf92471e491ff5fd75c192fd38e5

WORKDIR /app

COPY ./web-server/requirements.lock.txt .
RUN pip install --no-cache-dir -r requirements.lock.txt

COPY ./web-server/hass_cli_web.py .

CMD ["uvicorn", "hass_cli_web:app", "--host", "0.0.0.0", "--port", "3000"]
