import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hommie/features/sync/domain/entities/registry/registry_entry.dart';

part 'area_registry_entry.freezed.dart';
part 'area_registry_entry.g.dart';

/// [areaId] - [AreaRegistryEntry] Unique ID of area (generated by Home Assistant)
/// [name] - [AreaRegistryEntry] Name of this area
/// [picture] - [AreaRegistryEntry] Picture of this area
/// [aliases] - [AreaRegistryEntry] List of aliases for this area
@freezed
sealed class AreaRegistryEntry with _$AreaRegistryEntry {
  @JsonSerializable(fieldRename: FieldRename.snake)
  @Implements<RegistryEntry>()
  const factory AreaRegistryEntry({
    required double createdAt,
    required double modifiedAt,
    required List<String> aliases,
    required String areaId,
    String? floorId,
    String? humidityEntityId,
    String? icon,
    required List<String> labels,
    required String name,
    String? picture,
    String? temperatureEntityId,
  }) = _AreaRegistryEntry;

  factory AreaRegistryEntry.fromJson(Map<String, dynamic> json) =>
      _$AreaRegistryEntryFromJson(json);
}
